# Generated by Django 4.1 on 2022-08-24 03:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=70, null=True)),
                ('institution', models.CharField(max_length=140)),
                ('date_to', models.CharField(max_length=100)),
                ('date_from', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('date_to', models.CharField(max_length=100)),
                ('date_from', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('hero_text', ckeditor.fields.RichTextField(null=True)),
                ('facebook', models.URLField(max_length=25)),
                ('linkedin', models.URLField(max_length=25)),
                ('instagram', models.URLField(max_length=25)),
                ('youtube', models.URLField(max_length=25)),
                ('git', models.URLField(max_length=25)),
                ('behance', models.URLField(max_length=25)),
                ('about_me', ckeditor.fields.RichTextField(null=True)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('resume', models.FileField(blank=True, null=True, upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(max_length=50, null=True)),
                ('category', models.CharField(max_length=140, null=True)),
                ('technology', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=25, null=True)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('position', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('feedback', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
